const palette = {
  violet50: '#F5F3FF',
  violet100: '#EDE9FE',
  violet200: '#DDD6FE',
  violet300: '#C4B5FD',
  violet400: '#A78BFA',
  violet500: '#8B5CF6',
  violet600: '#7C3AED',
  violet700: '#6D28D9',
  violet800: '#5B21B6',
  violet900: '#4C1D95',
  amber300: '#FCD34D',
  amber400: '#FBBF24',
  amber500: '#F59E0B',
  amber600: '#D97706',
  amber700: '#B45309',
  obsidian950: '#0D0B14',
  obsidian900: '#1E1B2E',
  obsidian800: '#2D2A40',
  obsidian700: '#3D3A52',
  obsidian600: '#4D4A65',
  white: '#FFFFFF',
  gray50: '#F9FAFB',
  gray100: '#F3F4F6',
  gray200: '#E5E7EB',
  gray300: '#D1D5DB',
  gray400: '#9CA3AF',
  gray500: '#6B7280',
  gray600: '#4B5563',
  gray700: '#374151',
  gray800: '#1F2937',
  gray900: '#111827',
  successLight: '#059669',
  successDark: '#10B981',
  successBgLight: '#D1FAE5',
  successBgDark: '#064E3B',
  warningLight: '#D97706',
  warningDark: '#FBBF24',
  warningBgLight: '#FEF3C7',
  warningBgDark: '#78350F',
  dangerLight: '#DC2626',
  dangerDark: '#F87171',
  dangerBgLight: '#FEE2E2',
  dangerBgDark: '#7F1D1D',
  infoLight: '#0284C7',
  infoDark: '#38BDF8',
  infoBgLight: '#E0F2FE',
  infoBgDark: '#0C4A6E',
} as const;

export const lightColors = {
  primary: palette.violet600,
  primaryLight: palette.violet100,
  primaryDark: palette.violet900,
  accent: palette.amber500,
  accentLight: palette.amber300,
  accentDark: palette.amber700,
  background: palette.gray50,
  surface: palette.white,
  surfaceElevated: palette.white,
  card: palette.white,
  textPrimary: palette.gray900,
  textSecondary: palette.gray500,
  textDisabled: palette.gray300,
  textOnPrimary: palette.white,
  textOnAccent: palette.gray900,
  border: palette.gray200,
  borderFocus: palette.violet500,
  success: palette.successLight,
  successBg: palette.successBgLight,
  warning: palette.warningLight,
  warningBg: palette.warningBgLight,
  danger: palette.dangerLight,
  dangerBg: palette.dangerBgLight,
  info: palette.infoLight,
  infoBg: palette.infoBgLight,
  statusActive: palette.violet600,
  statusActiveBg: palette.violet100,
  statusInProgress: palette.amber500,
  statusInProgressBg: palette.warningBgLight,
  statusCompleted: palette.successLight,
  statusCompletedBg: palette.successBgLight,
  statusArchived: palette.gray400,
  statusArchivedBg: palette.gray100,
  priorityUrgent: '#DC2626',
  priorityHigh: '#F97316',
  priorityMedium: palette.amber500,
  priorityLow: palette.successLight,
  gradientPrimary: [palette.violet600, palette.violet900] as [string, string],
  gradientAccent: [palette.amber400, palette.amber600] as [string, string],
  gradientDark: [palette.obsidian900, palette.obsidian800] as [string, string],
  gradientCard: [palette.violet50, palette.white] as [string, string],
  tabBarBg: palette.white,
  tabBarActive: palette.violet600,
  tabBarInactive: palette.gray400,
  tabBarBorder: palette.gray200,
  overlay: 'rgba(0, 0, 0, 0.5)',
  shimmer: palette.gray200,
};

export const darkColors = {
  primary: palette.violet500,
  primaryLight: palette.obsidian700,
  primaryDark: palette.violet300,
  accent: palette.amber400,
  accentLight: palette.amber300,
  accentDark: palette.amber600,
  background: palette.obsidian950,
  surface: palette.obsidian900,
  surfaceElevated: palette.obsidian800,
  card: palette.obsidian800,
  textPrimary: palette.gray50,
  textSecondary: palette.gray400,
  textDisabled: palette.obsidian600,
  textOnPrimary: palette.white,
  textOnAccent: palette.gray900,
  border: palette.obsidian700,
  borderFocus: palette.violet400,
  success: palette.successDark,
  successBg: palette.successBgDark,
  warning: palette.warningDark,
  warningBg: palette.warningBgDark,
  danger: palette.dangerDark,
  dangerBg: palette.dangerBgDark,
  info: palette.infoDark,
  infoBg: palette.infoBgDark,
  statusActive: palette.violet400,
  statusActiveBg: palette.obsidian700,
  statusInProgress: palette.amber400,
  statusInProgressBg: palette.warningBgDark,
  statusCompleted: palette.successDark,
  statusCompletedBg: palette.successBgDark,
  statusArchived: palette.gray500,
  statusArchivedBg: palette.obsidian700,
  priorityUrgent: '#F87171',
  priorityHigh: '#FB923C',
  priorityMedium: palette.amber400,
  priorityLow: palette.successDark,
  gradientPrimary: [palette.violet800, palette.obsidian900] as [string, string],
  gradientAccent: [palette.amber600, palette.amber700] as [string, string],
  gradientDark: [palette.obsidian950, palette.obsidian900] as [string, string],
  gradientCard: [palette.obsidian800, palette.obsidian900] as [string, string],
  tabBarBg: palette.obsidian900,
  tabBarActive: palette.violet400,
  tabBarInactive: palette.obsidian600,
  tabBarBorder: palette.obsidian700,
  overlay: 'rgba(0, 0, 0, 0.75)',
  shimmer: palette.obsidian700,
};

export type AppColors = typeof lightColors;
